### ISSUE TITLE
etq modérateur, quand je termine ma modération en notifiant l'utilisateur, la demande est automatiquement marquée comme traitée

### ISSUE THREAD

**Issue by renardpal** [betagouv/hyyypertool#7]
dès qu'une notification est effectuée (peu importe le type de notification), la demande est marquée comme traitée.
le modérateur voit un écran de confirmation.
un btn "revenir à l'accueil" garde en mémoire la pagination / le filtre de la page d'accueil

CF : https://www.figma.com/file/73s6jT8QgfOZJRrKW4oc5t/HyperTool?type=design&node-id=64-3586&mode=design
▶️ pour la cinématique du parcours

**Comment by douglasduteil** [comment]
Done with #156
