### ISSUE TITLE
Ajouter un bouton pour consulter la liste des dirigeants d’une organisation sur l’Annuaire des Entreprises 

### ISSUE THREAD

**Issue by laetitiasanogo** [betagouv/hyyypertool#82]
### Describe the feature

_**Processus actuel**_ : 
1. Cliquer sur le bouton « Fiche sur l’Annuaire des Entreprises »,
2. Cliquer sur l’onglet « Dirigeants » une fois que l'on est sur la fiche.

**_Besoin_** : 
- Ajouter un bouton qui renvoie directement à l’onglet « Dirigeants » sur la Fiche Annuaire des Entreprises de l'organisation,
- Nommer le bouton « Liste des Dirigeants - Annuaire des Entreprises »,
- Placer ce nouveau bouton sous le bouton existant « Fiche sur l’Annuaire des Entreprises ».

**Comment by douglasduteil** [comment]
Done with https://github.com/betagouv/hyyypertool/pull/343 https://github.com/betagouv/hyyypertool/pull/344
