### ISSUE TITLE
Transformer le bouton « Envoyer une réponse via Zammad » en un bouton « Action en 1c clic... »

### ISSUE THREAD

**Issue by laetitiasanogo** [betagouv/hyyypertool#85]
### Describe the feature

Lorsque l’on refuse la modération avec l’envoi d’un mail via Zammad ou demande des informations complémentaires

**_Comportement actuel :_** 

1. On clique sur le bouton « Envoyer une réponse via Zammad », puis 
2. On est renvoyé vers le 1er mail transmis au demandeur 

**_Besoin :_** 

- Transformer le bouton actuel « Envoyer une réponse via Zammad » par un bouton « Action en 1 clic : Envoyer une réponse via Zammad et marquer comme traité »
- Être renvoyé en haut de page de la modération

**Comment by douglasduteil** [comment]
Done with #149
